---
- name: Remove default nginx vhost config file
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: reload nginx

- name: create /etc/nginx/sites-enabled directory
  file:
    path: "/etc/nginx/sites-enabled"
    state: directory

- name: wp vhost config
  template:
    src: wp.conf.j2
    dest: "/etc/nginx/sites-enabled/{{domain}}.conf"
    mode: 0644
  notify: reload nginx
